### PR TITLE
Billing Information Provider

### PR DESCRIPTION
**Pull request by darknesscoder**

### CODE REVIEW

**Comment by lukerollans** [comment]
Great, thanks! I will try my very hardest to take a look at this tonight and test

**Comment by lkraav** [comment]
Looks quite straightforward. @lukerollans did you have any conclusions on this from looking at this earlier in the year?

**Comment by lukerollans** [comment]
@darknesscoder @lkraav This looks good. I'll get it merged in very shortly.

**Comment by lkraav** [comment]
I have the billing address patch running live at https://checkout.conversionxl.com/live/

There's a double-digit amount of purchases and none have reported rejected credit card issues yet, unlike last year. It looks like this works.

**Comment by lukerollans** [comment]
@lkraav, great, thanks!

**Pull request merged**
